name: Run tests
on:
  workflow_dispatch:
  push:
    tags:        
      - v*.**

jobs:
    test:
        name: Run tests
        runs-on: ubuntu-latest
        container: obolibrary/odkfull
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Run build
            run: |
              cd src/ontology 
              make testcomposer install
